[project]
name = "fastapi-template-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "loguru>=0.7.3",
    "supabase>=2.17.0",
    "uvicorn>=0.35.0",
]
